// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJzlWkxSz4fgGObgB1jWrOEtjD9Efekm0',
    appId: '1:1032918344469:web:82e0ca9d4bf4d2034ebf1c',
    messagingSenderId: '1032918344469',
    projectId: 'myflutter-interview',
    authDomain: 'myflutter-interview.firebaseapp.com',
    storageBucket: 'myflutter-interview.appspot.com',
    measurementId: 'G-XKK1DS8VH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPUVbbGsn-RZxtVbaXLYw4PTxiSdvo_0Q',
    appId: '1:1032918344469:android:4a4b8e4658b3b3af4ebf1c',
    messagingSenderId: '1032918344469',
    projectId: 'myflutter-interview',
    storageBucket: 'myflutter-interview.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdK0PC2byn-QMeGyH6ybzwEy_QAHNsxlA',
    appId: '1:1032918344469:ios:298859dbc7442e8b4ebf1c',
    messagingSenderId: '1032918344469',
    projectId: 'myflutter-interview',
    storageBucket: 'myflutter-interview.appspot.com',
    iosBundleId: 'com.example.myflutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdK0PC2byn-QMeGyH6ybzwEy_QAHNsxlA',
    appId: '1:1032918344469:ios:bccfcbbd259a89e24ebf1c',
    messagingSenderId: '1032918344469',
    projectId: 'myflutter-interview',
    storageBucket: 'myflutter-interview.appspot.com',
    iosBundleId: 'com.example.myflutterTask.RunnerTests',
  );
}
